variables:
    KVER: "5.4"
    
before_script:
- "git remote add stable https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git || true"
- "git remote add mfd https://git.kernel.org/pub/scm/linux/kernel/git/lee/mfd.git || true"
- "git fetch --no-tags --multiple stable mfd"

stages:
- prep
- build

check:
    stage: prep
    script:
    - "git checkout -b $CI_JOB_ID $CI_COMMIT_SHA"
    - "git merge --no-stat --allow-unrelated-histories -X ours stable/linux-$KVER.y"
    - ./check

config:
    stage: prep
    script:
    - "git checkout -b $CI_JOB_ID $CI_COMMIT_SHA"
    - "git merge --no-stat --allow-unrelated-histories -X ours stable/linux-$KVER.y"
    - ./config
    artifacts:
        paths:
        - .config
        expire_in: "1 day"

build:
    stage: build
    script:
    - "git fetch --tags stable"
    - "git checkout -b $CI_JOB_ID stable/linux-$KVER.y"
    - "git merge mfd/ib-mfd-doc-sparc-libdevres-5.5 -m 'Merge lpss fixes'"
    - make -j$(nproc) bzImage
    - make -j$(nproc) modules
    - make tar-pkg
    - "make kernelrelease | tee latest"
    artifacts:
        paths:
        - linux-*.tar
        - .config
        - latest
        expire_in: "3 months"
