variables:
    KVER: "4.9"
    
before_script:
- "git remote add stable https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git || true"
- "git fetch --no-tags stable"

stages:
- config
- build

config:
    stage: config
    script:
    - "git checkout -b $CI_JOB_ID $CI_COMMIT_REF_NAME"
    - "git merge --no-stat --allow-unrelated-histories -X ours stable/linux-$KVER.y"
    - ./check
    - ./config
    artifacts:
        paths:
        - .config

build:
    stage: build
    script:
    - "git checkout -b $CI_JOB_ID stable/linux-$KVER.y"
    - make -j$$(nproc) bzImage
    - make -j$$(nproc) modules
    - make tar-pkg
    artifacts:
        paths:
        - linux-*.tar
        - .config
