before_script:
- "git remote add stable https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git || true"
- "git fetch --no-tags stable"
- "git checkout -b linux-4.9.y master"
- "git merge --allow-unrelated-histories -X ours stable/linux-4.9.y"

stages:
- config
- build

config:
    stage: config
    script:
    - make defconfig
    artifacts:
        paths:
        - .config

build:
    stage: build
    script:
    - ./build
    artifacts:
        paths:
        - linux-*.tar
