variables:
    KVER: "4.9"

before_script:
- "git remote add stable https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git || true"
- "git fetch --no-tags stable"
- "git checkout -b $CI_JOB_ID master || git checkout $CI_JOB_ID"
- "git merge --allow-unrelated-histories -X ours stable/linux-$KVER.y"

stages:
- config
- build

config:
    stage: config
    script:
    - make defconfig
    artifacts:
        paths:
        - .config

build:
    stage: build
    script:
    - ./build
    artifacts:
        paths:
        - linux-*.tar
        - .config
