variables:
    KVER: "4.9"
    
before_script:
- "git remote add stable https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git || true"
- "git fetch stable"

stages:
- prep
- build

check:
    stage: prep
    script:
    - "git checkout -b $CI_JOB_ID $CI_COMMIT_SHA"
    - "git merge --no-stat --allow-unrelated-histories -X ours stable/linux-$KVER.y"
    - ./check
    allow_failure: true

config:
    stage: prep
    script:
    - "git checkout -b $CI_JOB_ID $CI_COMMIT_SHA"
    - "git merge --no-stat --allow-unrelated-histories -X ours stable/linux-$KVER.y"
    - ./config
    artifacts:
        paths:
        - .config
        expire_in: "1 day"

build:
    stage: build
    script:
    - "git checkout -b $CI_JOB_ID stable/linux-$KVER.y"
    - make -j$(nproc) bzImage
    - make -j$(nproc) modules
    - make tar-pkg
    - "make kernelrelease | tee latest"
    artifacts:
        paths:
        - linux-*.tar
        - .config
        - latest
        expire_in: "3 months"
