#!/bin/bash

set -e

./scripts/config -e meta_options
./scripts/config -e meta_all

./scripts/config -d HAMRADIO
./scripts/config -d IPV6_SIT
./scripts/config --set-str UEVENT_HELPER_PATH "" || true
./scripts/config --set-val CONFIG_SND_HDA_PREALLOC_SIZE 2048 || true
./scripts/config -e LOCALVERSION_AUTO

make olddefconfig

make silentoldconfig
kver=$(make kernelrelease)

make -j$(grep -c MHz /proc/cpuinfo) bzImage
make -j$(grep -c MHz /proc/cpuinfo) modules
make tar-pkg
make kernelrelease
