#!/bin/bash

for i in $(awk '/^config/{print$2}' meta/Kconfig meta/features/* meta/hosts/*/*)
do
	make tinyconfig >/dev/null
	echo $i
	./scripts/config -e meta_options
	./scripts/config -e $i
	make olddefconfig | grep "^warning:"
done
