#!/bin/bash

set -e

make defconfig
./scripts/config -e meta_options
./scripts/config -e meta_all
./scripts/config -d DUMMY
./scripts/config -d HAMRADIO
./scripts/config -d IPV6_SIT
./scripts/config -d LOGO
./scripts/config --set-str UEVENT_HELPER_PATH "" || true
./scripts/config --set-val SND_HDA_PREALLOC_SIZE 2048 || true
./scripts/config -m SND_HDA_INTEL
./scripts/config -m RTL_CARDS
./scripts/config -m R8169
./scripts/config -m DRM_I915

./scripts/config -e PREEMPT_NONE
./scripts/config -d PREEMPT_VOLUNTARY
./scripts/config -d PREEMPT

./scripts/config -d PM_TRACE_RTC
./scripts/config -d CPU_FREQ_DEFAULT_GOV_USERSPACE
./scripts/config -e CPU_FREQ_DEFAULT_GOV_POWERSAVE


case "$HOSTNAME" in
	oak)
		./scripts/config -e LOCALVERSION_AUTO
		;;
esac

make olddefconfig
