#!/bin/bash

set -e

make defconfig
./scripts/config -e meta_options
./scripts/config -e meta_all
./scripts/config -d HAMRADIO
./scripts/config -d IPV6_SIT
./scripts/config -d LOGO
./scripts/config --set-str UEVENT_HELPER_PATH "" || true
./scripts/config --set-val CONFIG_SND_HDA_PREALLOC_SIZE 2048 || true
./scripts/config -m SND_HDA_INTEL
./scripts/config -m RTL_CARDS
./scripts/config -m R8169

./scripts/config -d PREEMPT_NONE
./scripts/config -d PREEMPT_VOLUNTARY
./scripts/config -e PREEMPT

./scripts/config -d PM_TRACE_RTC


case "$HOSTNAME" in
	solana|dys*)
		./scripts/config -m DRM_I915
		;&
	oak)
		./scripts/config -e LOCALVERSION_AUTO
		;;
esac

make olddefconfig
