#!/bin/bash

set -e

make defconfig
./scripts/config -e meta_options
./scripts/config -e meta_all
./scripts/config -d HAMRADIO
./scripts/config -d IPV6_SIT
./scripts/config --set-str UEVENT_HELPER_PATH "" || true
./scripts/config --set-val CONFIG_SND_HDA_PREALLOC_SIZE 2048 || true

case "$HOSTNAME" in
	solana)
		./scripts/config -m DRM_I915
		./scripts/config -m SND_HDA_INTEL
		;&
	oak)
		./scripts/config -e LOCALVERSION_AUTO
		;;
esac

make olddefconfig
make silentoldconfig
