#!/bin/bash

action=${1?-Need action (nconfig,check,build,merge)}
kver=${2:-6.1}
image=${3:-applehq/gentoo-stage4:latest}

if mountpoint -q /etc/hosts; then
	rsync --info=progress2 --recursive /usr/src/kconfig /
	pushd /kconfig

	case "$action" in
	merge|shell)	;;
	*)		gitargs="-X ours"
			;;
	esac
	git merge --no-stat --allow-unrelated-histories $gitargs stable/linux-$kver.y -m "Merge linux-$kver.y"

	case "$action" in
	merge)
		git mergetool --tool=vimdiff
		;;
	check)
		./check
		;;
	*config)
		make $action
		make nconfig
		;;
	build)
		./config
		./build
		;;
	shell)
		exec bash
		;;
	esac
else
	case "$action" in
	build)
		container=$(docker run --detach -v ${PWD}:/usr/src/kconfig $image /usr/src/kconfig/docker "$@")
		docker wait $container
		docker logs --tail 10 $container
		echo "$(cut -c-16 <<<$container):/kconfig/"
		;;
	shell|merge|*config)
		docker run --rm -it -v ${PWD}:/usr/src/kconfig $image /usr/src/kconfig/docker "$@"
		;;
	__complete*)
		compgen -W "build shell merge check allnoconfig defconfig"
		;;
	*)
		docker run --rm -v ${PWD}:/usr/src/kconfig $image /usr/src/kconfig/docker "$@"
		;;
	esac
fi
