# Workflow to build a custom kernel

name: kbuild

env:
  UPSTREAM: gregkh/linux
  BRANCH: linux-5.15.y

on:
  push:
  pull_request:
  schedule:
  - cron: "32 2 1,15 * 5"
  workflow_dispatch:

jobs:
  config:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
        - "5.10"
        - "5.15"
    steps:
    - name: Checkout kconfig source
      uses: actions/checkout@v2
      with:
        # Need full history to merge
        fetch-depth: 0

    - name: Checkout upstream source
      uses: actions/checkout@v2
      with:
        repository: ${{ env.UPSTREAM }}
        ref: linux-${{ matrix.branch }}.y
        path: linux-stable
        # Need full history to merge
        fetch-depth: 0

    - name: Merge the two unrelated branches
      run: |
        git fetch linux-stable
        git config user.name github-actions
        git config user.email github-actions@github.com
        git merge --no-stat --allow-unrelated-histories -X ours -m "Merge $BRANCH" FETCH_HEAD

    - name: Generate full kernel config
      run: ./config

    - name: Upload generated config
      uses: actions/upload-artifact@v2
      with:
        name: config-${{ matrix.branch }}
        path: .config
        if-no-files-found: error

  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
        - "5.10"
        - "5.15"
    steps:
    - name: Checkout kconfig source
      uses: actions/checkout@v2
      with:
        # Need full history to merge
        fetch-depth: 0

    - name: Checkout upstream source
      uses: actions/checkout@v2
      with:
        repository: ${{ env.UPSTREAM }}
        ref: linux-${{ matrix.branch }}.y
        path: linux-stable
        # Need full history to merge
        fetch-depth: 0

    - name: Merge the two unrelated branches
      run: |
        git fetch linux-stable
        git config user.name github-actions
        git config user.email github-actions@github.com
        git merge --no-stat --allow-unrelated-histories -X ours -m "Merge $BRANCH" FETCH_HEAD

    - name: Check kernel options
      run: ./check

  build:
    # build requires the full config
    needs: config
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
        - "5.10"
        - "5.15"
    steps:
    - name: Checkout upstream source
      uses: actions/checkout@v2
      with:
        repository: ${{ env.UPSTREAM }}
        ref: linux-${{ matrix.branch }}.y
        # Need full history for tags
        fetch-depth: 0

    - name: Download full config
      uses: actions/download-artifact@v2
      with:
        name: config-${{ matrix.branch }}

    - name: Build the kernel
      uses: docker://applehq/gentoo-stage4
      with:
        args: make -j3 tar-pkg

    - name: Configure environment
      run: echo KREL=$(make kernelrelease) >> ${GITHUB_ENV}

    - name: Create an initramfs
      uses: docker://applehq/gentoo-stage4
      with:
        args: dracut --xz --kmoddir tar-install/lib/modules/${{ env.KREL }}/ -f tar-install/boot/initrd-${{ env.KREL }} ${{ env.KREL }}

    - name: Change initrd permissions
      run: sudo chmod a+r tar-install/boot/initrd-${{ env.KREL }}

    - name: Upload compiled kernel binaries
      uses: actions/upload-artifact@v2
      with:
        name: kernel-${{ env.KREL }}
        if-no-files-found: error
        # Ignore the non-compressed kernel
        path: |
          tar-install/
          !tar-install/boot/vmlinux*
